services:
  webapp:
    build:
      dockerfile: Dockerfile
      #image: labsacrregistry.azurecr.io/myapp:latest
      context: . 
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 3001:3001