name: sample-products-ci-workflow

on:
  workflow_call:
    inputs:
      dotnetVersion:
        description: 'node version'
        required: true
        type: string
        default: '18'
     
env:
  
  NODE_VERSION: '16.x'                      # set this to the node version to use
  

jobs:
  sample-webapp-CI-job:
    runs-on: ubuntu-latest
    environment: sandbox
    
    steps:
  
    - name: 'Checkout Source Code'                                                                                                                                                                             
      uses: actions/checkout@v3

    - name: Cypress install
      uses: cypress-io/github-action@v6
      with:
        runTests: false
      # report machine parameters
    - run: yarn cypress info
    - run: node --version
    - run: node -p 'os.cpus()'
    - run: yarn types
    - run: yarn lint
    - run: yarn test:unit:ci
    - run: yarn build:ci
