name: sample-products-ci-workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        type: string
        default: 'debug'
    outputs:
      releaseVersion: 
        value: ${{ jobs.ra_version.outputs.release }}
        description: The release version generated in this build
      ra_version: 
        value: ${{ jobs.ra_version.outputs.version }}
        description: The version generated in this build
  push:
    branches:
      - main

jobs:
  ra_version:
    name: "Generate versions from common workflow"
    uses: ivanhidalgo22/cypress-lab/.github/workflows/raver.yml@v1
  sample-webapp-CI-job:
    runs-on: ubuntu-latest
    environment: sandbox
    
    steps:
  
    - name: 'Checkout Source Code'                                                                                                                                                                             
      uses: actions/checkout@v3

    - name: Cypress install
      uses: cypress-io/github-action@v6
      with:
        runTests: false
      # report machine parameters
    - run: yarn cypress info
    - run: node --version
    - run: node -p 'os.cpus()'
    - run: yarn types
    - run: yarn lint
    - run: yarn test:unit:ci
    - run: yarn build:ci
