name: sample-products-ci-workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        type: string
        default: 'debug'
      working_directory:
        type: string
        description: 'Directory for execute de CI Workflow'     
        required: true
        default: 'build'
    outputs:
      releaseVersion: 
        value: ${{ jobs.ra_version.outputs.release }}
        description: The version generated in this build
    
  #push:
    #branches:
      #- main
    

jobs:
  ra_version:
    name: "Generate versions from common workflow"
    uses: ./.github/workflows/raver.yml
  sample-webapp-CI-job:
    runs-on: ubuntu-latest
    environment: sandbox
    
    steps:
  
    - name: 'Checkout Source Code'                                                                                                                                                                             
      uses: actions/checkout@v3

    - name: Cypress install
      uses: cypress-io/github-action@v6
      with:
        runTests: false
      # report machine parameters
    - run: yarn cypress info
    - run: node --version
    - run: node -p 'os.cpus()'
    - run: yarn types
    - run: yarn lint
    - run: yarn test:unit:ci
    - run: yarn build:ci

    - name: Save build folder
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.ra_version.outputs.version }}
        path: ${{ inputs.working_directory }}/${{ needs.ra_version.outputs.version }}.zip
        if-no-files-found: error
